version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=warehouse_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DEBUG=True
    depends_on:
      - db
  
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=warehouse_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
